web/views/results.py
import os
import pandas as pd
from dotenv import load_dotenv
from flask import request, session, Blueprint, render_template, send_file
from views.auth import login_required
from services.API import get
from utils.mixins import save_archivo, obtener_archivo_json, set_date_format

load_dotenv()

endopoint = 'results/'

Result = Blueprint('Result', __name__)

upload_folder = os.getcwd()+'/uploads'


@Result.route('/preparations')
@Result.route('/preparations/<conjunto>')
@login_required
def preparations(conjunto=None):
    if conjunto:
        return list_set('preparations', conjunto)
    return get_list('preparations')


@Result.route('/executions')
@Result.route('/executions/<conjunto>')
@login_required
def executions(conjunto=None):
    if conjunto:
        return list_set('executions', conjunto)
    return get_list('executions')


def get_list(results):
    rol = 'preparador' if results == 'preparations' else 'ejecutor'
    status, body = get(results+'/'+rol+'/'+session['user']['correo'])
    if status:
        return render_template(endopoint+results+'.html', results=set_date_format(body))
    else:
        return render_template(endopoint+results+'.html', results=[], error=body)


def list_set(results, conjunto):
    status, body = get(results+'/set/'+conjunto)
    if status:
        return render_template(endopoint+results+'.html', results=set_date_format(body))
    else:
        return render_template(endopoint+results+'.html', results=[], error=body)


@Result.route('/ejecucion/detalle', methods=['POST'])
@login_required
def ejecucion_detalle():
    body = dict(request.values)
    ejecucion = body['ejecucion']

    # Obtener el archivo de desertores
    archivo = 'D '+ejecucion
    ruta = upload_folder+'/desertores/'+archivo
    exito, desertores = obtener_archivo_json(ruta)

    status, body = get('executions/'+ejecucion)

    if status and exito:
        del body['precision_model']
        del body['numero']
        return render_template(endopoint+'ejecucion_detalle.html', desertores=desertores, results=body.pop('results'), ejecucion=body)
    elif status and not (exito):
        if body['estado'] == 'Fallida':
            del body['precision_model']
            del body['numero']
            return render_template(
                endopoint+'ejecucion_detalle.html',
                desertores=None,
                results=body.pop('results'),
                ejecucion=body
            )
        else:
            return desertores
    else:
        return render_template(
            'utils/mensaje.html',
            mensaje='No se obtener la ejecución',
            submensaje=body
        )


@Result.route('/preparacion/detalle', methods=['POST'])
@login_required
def preparacion_detalle():
    body = dict(request.values)
    preparacion = body['preparacion']
    status, body = get('preparations/'+preparacion)

    if status:
        del body['numero']
        return render_template(
            endopoint+'preparacion_detalle.html',
            observaciones=body.pop('observaciones'),
            p=body
        )
    else:
        return render_template(
            'utils/mensaje.html',
            mensaje='No se obtener los resultaods de la ejecución',
            submensaje=body
        )


@Result.route('/descargar/desertores/<ejecucion>', methods=['GET'])
@login_required
def download(ejecucion):
    status_c, body_c = get('executions/'+ejecucion)
    if not status_c:
        return render_template('utils/mensaje.html', mensaje='No existe esa ejecución')

    archivo = 'D '+ejecucion
    ruta = upload_folder+'/desertores/'+archivo
    try:
        data = pd.read_json(ruta+'.json')
    except Exception as e:
        return render_template(
            'utils/mensaje.html',
            mensaje='No se pudo abrir el archivo de desertores:',
            submensaje=str(e)
        )

    exito, pagina_error = save_archivo(data, ruta+'.xls', 'excel')
    if not (exito):
        return pagina_error

    return send_file(ruta+'.xls', as_attachment=True)

web/views/sets.py
import traceback
import pandas as pd
import os
import json
import logging
import utils.dashboards.data_ies as DataIES

from flask import request, session, Blueprint, render_template, redirect, send_file, url_for, jsonify, flash
from dotenv import load_dotenv
from ast import literal_eval
from googletrans import Translator

from utils.model import prepare_data, verify_data, execute_model
from views.auth import login_required
from services.API import get, post, put

from utils.mixins import actualizar_state, save_archivo, save_ejecucion, save_preparacion, get_now_date, obtener_archivo_excel, obtener_nombre_conjunto

model_logger = logging.getLogger('model_logger')
error_logger = logging.getLogger('error_logger')

load_dotenv()

Set = Blueprint('Set', __name__)

endopoint = 'sets/'

upload_folder = os.getcwd()+'/uploads'

translator = Translator()


@Set.route('')
@Set.route('/')
@Set.route('/crudos')
@Set.route('/crudos/')
@login_required
def crudos():
    return get_list('crudos')


@Set.route('/procesados')
@Set.route('/procesados/')
@Set.route('/procesados/<conjunto>')
@login_required
def procesados(conjunto=None):
    if conjunto:
        return get_list('procesados', str(conjunto))
    return get_list('procesados')


def get_list(estado, conjunto=None):
    user = session.get('user', {'correo': ''}).get('correo')
    status_p, body_p = get('programs')
    status_c, body_c = get(
        f'sets/encargado/{user}?estado={estado}'
    )

    if status_c and status_p:
        if conjunto:
            body_c = [d for d in body_c if conjunto in d['nombre']]
        return render_template(
            endopoint+estado.replace(' ', '_')+'.html',
            sets=body_c,
            programs=body_p
        )

    if not status_c and not status_p:
        error = {**body_c, **body_p}
    elif not status_c:
        error = body_c
    else:
        error = body_p
    return render_template(
        endopoint+estado.replace(' ', '_')+'.html',
        sets=[],
        error=error
    )


@Set.route('/descargar/<estado>/<nombre>')
def download(estado, nombre):

    status_c, body_c = get('sets/'+nombre)
    if not status_c:
        return render_template('utils/mensaje.html', mensaje='No existe ese conjunto')

    if estado.lower() == 'crudos':
        nombre = 'C '+nombre
    elif estado.lower() == 'procesados':
        nombre = 'P '+nombre
    else:
        return render_template('utils/mensaje.html', mensaje='Estado del conjunto incorrecto')

    ruta = upload_folder+'/'+estado.lower()+'/'+nombre

    if os.path.exists(ruta+'.xlsx'):
        return send_file(ruta+'.xlsx', as_attachment=True)
    elif os.path.exists(ruta+'.xls'):
        return send_file(ruta+'.xls', as_attachment=True)
    else:
        return render_template('utils/mensaje.html', mensaje='No se encontro el archivo a descargar')


@Set.route('/crear')
@Set.route('/crear/')
@login_required
def post_create():
    periods = DataIES.get_periods_origen()
    status_f, body_f = get('faculties')
    status_p, body_p = get('programs')

    if status_f and status_p and periods:
        return render_template(endopoint+'crear.html', faculties=body_f, programs=body_p)
    elif not status_f and not status_p:
        error = {**body_f, **body_p}
    elif not status_f:
        error = body_f
    else:
        error = body_p
    return render_template('utils/mensaje.html', mensaje='No se pudieron cargar las programs y las faculties', submensaje=error)


@Set.route('crear/periods/programa/<int:programa>')
@login_required
def get_periods_program(programa):
    status, body = get(
        'desertion/students/periods/programa/{}'.format(programa))
    if status:
        return jsonify(body)
    return jsonify([])


@Set.route('/detalle', methods=['POST'])
@login_required
def detalle():
    # Obtener Lo valores del formulario
    body = dict(request.values)
    conjunto = literal_eval(body['conjunto'])
    # Consultas para mostrar info
    status_f, body_f = get('faculties')
    status_p, body_p = get('programs')
    status_u, body_u = get('users')

    if status_p and status_f and status_u and conjunto:
        return render_template(endopoint+'detalle.html', faculties=body_f, programs=body_p, users=body_u, c=conjunto)
    elif not status_f and not status_p and not status_u:
        error = {**body_f, **body_p, **body_u}
    elif not status_f:
        error = body_f
    elif not status_p:
        error = body_p
    elif not conjunto:
        return render_template('utils/mensaje.html', mensaje='No se encontro un conjunto para detallar')
    else:
        error = body_u
    return render_template('utils/mensaje.html', mensaje='No se pudieron cargar los datos para detallar el conjunto', submensaje=error)


@Set.route('/crear', methods=['POST'])
@Set.route('/crear/', methods=['POST'])
@login_required
def post_save(conjunto=None):
    if not conjunto:
        # Obtener Lo valores del formulario
        conjunto = dict(request.values)
    # Preparar conjunto para la insercion
    del conjunto['faculty']

    # TODO NEW! version 2 v2.0.0
    session['period_closed'] = (conjunto.get('period_closed') == 'on')
    if session.get('period_closed'):
        del conjunto['period_closed']

    conjunto['estado'] = 'Crudos'
    conjunto['periodoInicial'] = int(conjunto['periodoInicial'])
    conjunto['periodoFinal'] = int(conjunto['periodoFinal'])
    conjunto['programa'] = int(conjunto['programa'])
    conjunto['encargado'] = session['user']['correo']

    tipo = conjunto.get('tipo', 'consulta')
    archivo = request.files.get('archivo')
    ruta = upload_folder+'/crudos'

    # Guardar archivo en Upload folder

    ############# ARCHIVO ##############
    if (archivo and archivo.filename and tipo == 'excel'):
        extension = '.'+archivo.filename.split('.')[1]
        # Guardar archivo de excel

        if extension not in ['.xls', '.xlsx']:
            return render_template('utils/mensaje.html', mensaje='Extension de archivo incorrecta: '+str(extension), submensaje='Solo se permiten archivos excel .xls & xlsx')

        # VERIFICACION de formato
        data = pd.read_excel(archivo)
        validacion, mensaje_error, data_verificada, periodoInicial = verify_data(
            data, conjunto.get('periodoInicial'), conjunto.get('periodoFinal'), conjunto.get('programa'))
        conjunto['periodoInicial'] = periodoInicial

        # Obtener nombre del conjunto desde el api
        nombre, numero = obtener_nombre_conjunto(conjunto)
        if not nombre:
            return numero
        archivo_save = 'C ' + nombre + '.xlsx'

        if validacion:
            try:
                data_verificada.to_excel(
                    ruta+'/'+archivo_save,
                    engine='openpyxl',
                    index=False
                )
            except Exception as e:
                error_logger.error(e)
                return render_template('utils/mensaje.html', mensaje='Ocurrió un error guardando el conjunto de datos')
        else:
            return render_template('utils/mensaje.html', mensaje='Incorrecto el formato de la fuente de datos', submensaje=mensaje_error)

    ############# CONSULTA ##############
    # elif tipo == 'consulta':
    else:
        # Obtener datos de los students en ese programs y periods
        endpoint_conjunto = 'desertion/students/set/{}/{}/{}'
        endpoint_conjunto_values = endpoint_conjunto.format(
            conjunto['programa'], conjunto['periodoInicial'], conjunto['periodoFinal'])
        status, body = get(endpoint_conjunto_values)
        if status:
            data = pd.DataFrame(body)
        else:
            return render_template('utils/mensaje.html', mensaje='Consulta fallida a la base de datos')

        # VERIFICACION de formato
        validacion, mensaje_error, data_verificada, periodoInicial = verify_data(
            data, conjunto.get('periodoInicial'), conjunto.get('periodoFinal'), conjunto.get('programa'))
        conjunto['periodoInicial'] = periodoInicial

        # Obtener nombre del conjunto desde el api
        nombre, numero = obtener_nombre_conjunto(conjunto)
        if not nombre:
            return numero
        archivo_save = 'C ' + nombre + '.xlsx'

        if validacion:
            # Guardar tabla sql como excel
            try:
                data_verificada.to_excel(
                    ruta+'/'+archivo_save,
                    engine='openpyxl',
                    index=False
                )
            except Exception as e:
                error_logger.error(e)
                return render_template('utils/mensaje.html', mensaje='Ocurrió un error guardando el conjunto de datos')
        else:
            return render_template('utils/mensaje.html', mensaje='Incorrecto el formato de la fuente de datos', submensaje=mensaje_error)
    # else:
    #     return render_template('utils/mensaje.html', mensaje='Formulario incorrecto', submensaje='Verifica el formulario de creacion o notifica al Administrador del sistema')

    # Guardar registro de conjunto en la BD
    conjunto['nombre'] = nombre
    conjunto['numero'] = numero
    status, body = post('sets', conjunto)

    # TODO DEPRECATED! version 1 v1.5.0
    # if status:
    #     return redirect(url_for('Set.crudos'))

    # TODO NEW! version 2 v2.0.0
    if status:
        # preparar() luego de post_save()
        return preparar(conjunto)

    return render_template('utils/mensaje.html', mensaje='No se pudo save el conjunto', submensaje=body)


@Set.route('/preparar', methods=['POST'])
@login_required
def preparar(conjunto=None):
    if not conjunto:
        # Obtener Lo valores del formulario
        body = dict(request.values)
        conjunto = literal_eval(body['conjunto'])

    nombre = conjunto['nombre']

    # Actualizar conjunto de datos de crudo a en proceso
    act_state = actualizar_state(nombre, 'En Proceso')
    if act_state:
        return act_state

    # Crear prepraracion
    preparacion = {}

web/templates/results/ejecuciones.html
{% include 'components/header.html' %}

{% with menu='results' %}
    {% include 'components/sidebar.html' %}
{% endwith %}

<h4>Resultados</h4>
<br>

<!-- Input de filtrado -->
<div class="row ml-1 mt-2">
  &nbsp;<i class="fas fa-filter mr-2 mt-2""></i>&nbsp;
  <input type=" text" class="form-control form-control-sm w-25" id="filtroTabla" placeholder="Filtrar tabla...">
</div>
<br>

<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link text-dark  bg-light border" href="{{url_for('Result.preparations')}}">Preparaciones</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active text-dark" href="#">Ejecuciones</a>
  </li>
</ul>
<div class="table-responsive-sm">
  <table class="table table-hover table-sm" id="tabla">
    <thead>
      <tr>
        <th scope="col" class="border-top-0">
          <center>Ejecucion</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Fecha</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Duracion</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Estado</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Acciones</center>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for e in results %}
      <tr>
        <td>
          <center>{{ e.nombre }}</center>
        </td>
        <td>
          <center>{{ e.fechaInicial }}</center>
        </td>
        <td>
          <center>{{  '{:.2f}'.format(e.duracion/60)  }} &nbsp;min</center>
        </td>
        <td>
          <center>{{ e.estado }} </center>
        </td>
        <td>
          <center>
            <!--Ver Ejecuciones -->
            <form action="{{url_for('Result.ejecucion_detalle')}}" method="POST">
              <input type="hidden" name="ejecucion" value="{{e.nombre}}">
              <button type="submit" data-toggle="tooltip" data-placement="bottom" title="Ver Detalle"
                class="btn btn-outline-dark btn-sm submit" role="status">
                <i class="fas fa-search-plus"></i>
              </button>
            </form>
          </center>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<br>

{% if error %}
{% with titulo='No se pudieron cargar los results',error=error %}
{% include "components/alert.html" %}
{% endwith %}
{% endif %}


{% include 'components/footer.html' %}

web/templates/results/executions.html
{% include 'components/header.html' %}

{% with menu='results' %}
    {% include 'components/sidebar.html' %}
{% endwith %}

<h4>Resultados</h4>
<br>

<!-- Input de filtrado -->
<div class="row ml-1 mt-2">
  &nbsp;<i class="fas fa-filter mr-2 mt-2""></i>&nbsp;
  <input type=" text" class="form-control form-control-sm w-25" id="filtroTabla" placeholder="Filtrar tabla...">
</div>
<br>

<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link text-dark  bg-light border" href="{{url_for('Result.preparations')}}">Preparaciones</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active text-dark" href="#">Ejecuciones</a>
  </li>
</ul>
<div class="table-responsive-sm">
  <table class="table table-hover table-sm" id="tabla">
    <thead>
      <tr>
        <th scope="col" class="border-top-0">
          <center>Ejecucion</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Fecha</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Duracion</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Estado</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Acciones</center>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for e in results %}
      <tr>
        <td>
          <center>{{ e.nombre }}</center>
        </td>
        <td>
          <center>{{ e.fechaInicial }}</center>
        </td>
        <td>
          <center>{{  '{:.2f}'.format(e.duracion/60)  }} &nbsp;min</center>
        </td>
        <td>
          <center>{{ e.estado }} </center>
        </td>
        <td>
          <center>
            <!--Ver Ejecuciones -->
            <form action="{{url_for('Result.ejecucion_detalle')}}" method="POST">
              <input type="hidden" name="ejecucion" value="{{e.nombre}}">
              <button type="submit" data-toggle="tooltip" data-placement="bottom" title="Ver Detalle"
                class="btn btn-outline-dark btn-sm submit" role="status">
                <i class="fas fa-search-plus"></i>
              </button>
            </form>
          </center>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<br>

{% if error %}
{% with titulo='No se pudieron cargar los results',error=error %}
{% include "components/alert.html" %}
{% endwith %}
{% endif %}


{% include 'components/footer.html' %}

web/templates/results/preparacion_detalle.html
{% include 'components/header.html' %} {% with menu='results' %} {% include
'components/sidebar.html' %} {% endwith %}

<h4>Detalles de una Preparacion</h4>
<br />

{% if observaciones %}
<div class="container pt-3 pl-5 float-left border rounded">
  {% else %}
  <div class="container pt-3 pl-5 float-left">
    {% endif %}

    <div class="row">
      <div class="col">
        {% if observaciones %}
        <h5 class="mb-3 font-weight-bold">Detalle</h5>
        {% endif %}

        <table class="table table-bordered w-75">
          <tbody>
            {% for key, value in p.items() %}
            <tr>
              <td><strong>{{ key.title() }}</strong></td>
              <td class="bg-light">
                {{ value }} {% if key=='duracion' %} seg {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        <br />

        <div class="col-sm-11 d-flex justify-content-center align-items-center">
          <i class="fa fa-download" aria-hidden="true"></i>
          &nbsp;
          <strong class="mr-2 d-flex">Descargar: </strong>
          &nbsp;&nbsp;
          <a
            class="btn bg-white btn-sm border text-dark"
            type="button"
            href="{{url_for('Set.download',estado='procesados',nombre=p.conjunto)}}"
          >
            <i class="fas fa-file-excel mr-1"></i>
            Procesado
          </a>
        </div>

        <br /><br />

        {% if not observaciones %}
        <div class="text-center ml-0 pl-0 mr-5 pr-5">
          <!-- TODO NEW! version 2 v2.0.0 -->
          <button href="#" class="btn btn-outline-dark" onclick="goBack()">Atras</a>
          <!-- <a class="btn btn-outline-dark ml-0 mr-3" href="{{url_for('Result.preparations')}}">Atras</a> -->
        </div>
        {% endif %}

        <br />
      </div>

      {% if observaciones %} {% if observaciones is mapping %}
      <div class="col">
        <h5 class="mb-3 font-weight-bold">Observaciones</h5>

        <table class="table table-bordered w-75">
          <tbody>
            {% for key, value in observaciones.items() %}
            <tr>
              <td><strong>{{ key.title() }}</strong></td>
              <td class="bg-light">{{ value }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% endif %} {% endif %}
    </div>
    {% if observaciones %}
    <div class="row">
      <div class="col">
        <center>
          <!-- TODO NEW! version 2 v2.0.0 -->
          <button type="button" onclick="goBack()" class="btn btn-outline-dark ml-0 mr-3">Atras</a>
        </center>
      </div>
    </div>
    <br />
    {% endif %}
  </div>

  {% include 'components/footer.html' %}
</div>

web/templates/results/preparaciones.html
{% include 'components/header.html' %}

{% with menu='results' %}
    {% include 'components/sidebar.html' %}
{% endwith %}

<h4>Resultados</h4>
<br>

<!-- Input de filtrado -->
<div class="row ml-1 mt-2">
  &nbsp;<i class="fas fa-filter mr-2 mt-2""></i>&nbsp;
  <input type=" text" class="form-control form-control-sm w-25" id="filtroTabla" placeholder="Filtrar tabla...">
</div>
<br>

<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link active" href="#">Preparaciones</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-dark bg-light border" href="{{url_for('Result.executions')}}">Ejecuciones</a>
  </li>
</ul>
<div class="table-responsive-sm">
  <table class="table table-hover table-sm" id="tabla">
    <thead>
      <tr>
        <th scope="col" class="border-top-0">
          <center>Preparacion</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Fecha</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Duracion</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Estado</center>
        </th>
        <th scope="col" class="border-top-0">
          <center> Acciones</center>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for p in results %}
      <tr>
        <td>
          <center>{{ p.nombre }}</center>
        </td>
        <td>
          <center>{{ p.fechaInicial }}</center>
        </td>
        <td>
          <center>{{ p.duracion }} seg</center>
        </td>
        <td>
          <center>{{ p.estado }}</center>
        </td>
        <td>
          <!-- ACCCIONES -->
          <center>
            <div class="btn-group" role="group" aria-label="Basic example">
              <form action="{{url_for('Result.preparacion_detalle')}}" method="POST">
                <input type="hidden" name="preparacion" value="{{p.nombre}}">
                <button type="submit" data-toggle="tooltip" data-placement="bottom" title="Ver Detalle"
                  class="btn btn-outline-dark btn-sm submit" role="status">
                  <i class="fas fa-search-plus"></i>
                </button>
              </form>
            </div>
          </center>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<br>

{% if error %}
{% with titulo='No se pudieron cargar los results',error=error %}
{% include "components/alert.html" %}
{% endwith %}
{% endif %}


{% include 'components/footer.html' %}

web/templates/results/preparation_detail.html
{% include 'components/header.html' %} {% with menu='results' %} {% include
'components/sidebar.html' %} {% endwith %}

<h4>Detalles de una Preparacion</h4>
<br />

{% if observaciones %}
<div class="container pt-3 pl-5 float-left border rounded">
  {% else %}
  <div class="container pt-3 pl-5 float-left">
    {% endif %}

    <div class="row">
      <div class="col">
        {% if observaciones %}
        <h5 class="mb-3 font-weight-bold">Detalle</h5>
        {% endif %}

        <table class="table table-bordered w-75">
          <tbody>
            {% for key, value in p.items() %}
            <tr>
              <td><strong>{{ key.title() }}</strong></td>
              <td class="bg-light">
                {{ value }} {% if key=='duracion' %} seg {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        <br />

        <div class="col-sm-11 d-flex justify-content-center align-items-center">
          <i class="fa fa-download" aria-hidden="true"></i>
          &nbsp;
          <strong class="mr-2 d-flex">Descargar: </strong>
          &nbsp;&nbsp;
          <a
            class="btn bg-white btn-sm border text-dark"
            type="button"
            href="{{url_for('StudentSet.download',estado='procesados',nombre=p.conjunto)}}"
          >
            <i class="fas fa-file-excel mr-1"></i>
            Procesado
          </a>
        </div>

        <br /><br />

        {% if not observaciones %}
        <div class="text-center ml-0 pl-0 mr-5 pr-5">
          <!-- TODO NEW! version 2 v2.0.0 -->
          <button href="#" class="btn btn-outline-dark" onclick="goBack()">Atras</a>
          <!-- <a class="btn btn-outline-dark ml-0 mr-3" href="{{url_for('Result.preparations')}}">Atras</a> -->
        </div>
        {% endif %}

        <br />
      </div>

      {% if observaciones %} {% if observaciones is mapping %}
      <div class="col">
        <h5 class="mb-3 font-weight-bold">Observaciones</h5>

        <table class="table table-bordered w-75">
          <tbody>
            {% for key, value in observaciones.items() %}
            <tr>
              <td><strong>{{ key.title() }}</strong></td>
              <td class="bg-light">{{ value }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% endif %} {% endif %}
    </div>
    {% if observaciones %}
    <div class="row">
      <div class="col">
        <center>
          <!-- TODO NEW! version 2 v2.0.0 -->
          <button type="button" onclick="goBack()" class="btn btn-outline-dark ml-0 mr-3">Atras</a>
        </center>
      </div>
    </div>
    <br />
    {% endif %}
  </div>

  {% include 'components/footer.html' %}
</div>

web/templates/results/preparations.html
{% include 'components/header.html' %}

{% with menu='results' %}
    {% include 'components/sidebar.html' %}
{% endwith %}

<h4>Resultados</h4>
<br>

<!-- Input de filtrado -->
<div class="row ml-1 mt-2">
  &nbsp;<i class="fas fa-filter mr-2 mt-2""></i>&nbsp;
  <input type=" text" class="form-control form-control-sm w-25" id="filtroTabla" placeholder="Filtrar tabla...">
</div>
<br>

<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link active" href="#">Preparaciones</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-dark bg-light border" href="{{url_for('Result.executions')}}">Ejecuciones</a>
  </li>
</ul>
<div class="table-responsive-sm">
  <table class="table table-hover table-sm" id="tabla">
    <thead>
      <tr>
        <th scope="col" class="border-top-0">
          <center>Preparacion</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Fecha</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Duracion</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Estado</center>
        </th>
        <th scope="col" class="border-top-0">
          <center> Acciones</center>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for p in results %}
      <tr>
        <td>
          <center>{{ p.nombre }}</center>
        </td>
        <td>
          <center>{{ p.fechaInicial }}</center>
        </td>
        <td>
          <center>{{ p.duracion }} seg</center>
        </td>
        <td>
          <center>{{ p.estado }}</center>
        </td>
        <td>
          <!-- ACCCIONES -->
          <center>
            <div class="btn-group" role="group" aria-label="Basic example">
              <form action="{{url_for('Result.preparacion_detalle')}}" method="POST">
                <input type="hidden" name="preparacion" value="{{p.nombre}}">
                <button type="submit" data-toggle="tooltip" data-placement="bottom" title="Ver Detalle"
                  class="btn btn-outline-dark btn-sm submit" role="status">
                  <i class="fas fa-search-plus"></i>
                </button>
              </form>
            </div>
          </center>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<br>

{% if error %}
{% with titulo='No se pudieron cargar los results',error=error %}
{% include "components/alert.html" %}
{% endwith %}
{% endif %}


{% include 'components/footer.html' %}