web/utils/model/__init__.py
from .verification import verify_data
from .preparation import prepare_data
from .training import execute_model
from .prediction import predict

web/views/analist.py
import os
import json
import logging
import pandas as pd
from ast import literal_eval
from dotenv import load_dotenv
from flask import request, session, Blueprint, render_template, send_file, redirect, url_for, jsonify, flash

import utils.model as Modelo
from services.API import get, post
import views.sets as sets
from views.auth import login_required
import utils.dashboards.data_ies as DataIES
from utils.mixins import save_archivo, save_ejecucion, get_now_date, obtener_nombre_ejecucion

load_dotenv()

error_logger = logging.getLogger('error_logger')

endopoint = 'analist/models/'

Analista = Blueprint('Analista', __name__)

upload_folder = os.getcwd()+'/uploads'
models_folder = f'{upload_folder}/models'


@Analista.route('/models', methods=['GET'])
@Analista.route('/models/', methods=['GET'])
@login_required
def models():
    model = request.args.get('model')
    success, body = get_models(model)

    if not success:
        flash('User aún no tiene models de deserción', 'warning')
        body = []

    return render_template(
        'analist/models/listar.html',
        models=body,
    )


@Analista.route('/models/entrenar', methods=['GET', 'POST'])
@login_required
def entrenar():
    if request.method == 'GET':
        return formulario_entrenar()
    conjunto = dict(request.values)
    return sets.post_save(conjunto)


@Analista.route('/models/predecir', methods=['POST'])
def predecir():
    model = dict(request.values).get('model')
    return render_template(
        endopoint+'predecir.html',
        model=literal_eval(model)
    )


@Analista.route('/entrenamientos', methods=['GET'])
@Analista.route('/entrenamientos/', methods=['GET'])
@login_required
def entrenamientos():
    model = request.args.get('model')
    success, body = get_models(model)

    if not success:
        flash('User aún no tiene entrenamientos', 'info')
        body = []

    return render_template(
        'analist/entrenamientos.html',
        entrenamientos=body,
    )


@Analista.route('/predicciones', methods=['GET'])
@Analista.route('/predicciones/', methods=['GET'])
@login_required
def predicciones():
    model = request.args.get('model')
    success, body = get_models(model)

    if not success:
        flash('User aún no tiene predicciones', 'info')
        body = []

    return render_template(
        'analist/predicciones.html',
        predicciones=body,
    )


@Analista.route('/predicciones/predecir', methods=['POST'])
def predecir_model():
    form = dict(request.values)
    ejecucion = literal_eval(form.get('ejecucion'))
    ejecucion['fechaInicial'] = get_now_date()

    periodo = form.get('periodo')
    results = ejecucion.pop('results')
    model = ejecucion.get('conjunto')
    idprograma = results.get('idprograma')

    basic_info = {
        'idprograma': idprograma,
        'programa': results.get('programa'),
        'idfacultad': results.get('idfacultad'),
        'faculty': results.get('faculty'),
        'model': model
    }

    # Obtener students a predecir
    data_a_predecir = DataIES.get_students_period_program(
        periodo, idprograma
    )

    # Preparar data
    df_data_a_predecir = pd.DataFrame(data_a_predecir)
    data_preparada = Modelo.prepare_data(df_data_a_predecir)

    # Predecir results
    resultados_model, resultados_desertores = Modelo.predict(
        data_preparada, periodo, basic_info
    )
    resultados_desertores['idprograma'] = resultados_desertores['idprograma'].astype(
        int
    )
    resultados_desertores['semestre_prediccion'] = resultados_desertores['semestre_prediccion'].astype(
        int
    )

    # Insertar los results
    if resultados_desertores.empty:
        flash('No hay desertores para esta predicción', 'warning')
        return redirect(url_for('Analista.models'))

    resultados_insert = json.loads(
        resultados_desertores.to_json(orient='records')
    )

    status_insert, body_insert = post(
        'desertion/results',
        resultados_insert
    )

    if not status_insert:
        error_logger.error(
            'Error insertando los nuevos desertores'.format(
                json.dumps(body_insert))
        )
        raise Exception(
            'Ocurrió un error insertando y/o actualizando los results'
        )

    ejecucion['nombre'], ejecucion['numero'] = obtener_nombre_ejecucion(model)

    # Guardar desertotres
    archivo_desertores = f"D {ejecucion.get('nombre')}.json"
    ruta = upload_folder+'/desertores/'+archivo_desertores
    save_archivo(
        resultados_model.pop('desertores'), ruta, 'json'
    )

    # Guardar ejecución
    resultados_model['duracion'] = ejecucion.pop('duracion')
    save_ejecucion(ejecucion, resultados_model, 'Exitosa')
    flash('Predicción exitosa!!', 'success')

    return redirect(url_for('Analista.predicciones'))


@Analista.route('/models/descargar', methods=['POST'])
@login_required
def download():
    model = dict(request.values).get('model')
    ruta = f'{models_folder}/{model}.pkl'

    if os.path.exists(ruta):
        return send_file(ruta, as_attachment=True)

    success, body = get_models()

    flash('No se encontro el archivo a descargar', 'warning')

    if not success:
        flash(f"{body.get('error')}", 'danger')

    return render_template(
        'analist/models/listar.html',
        models=body,
    )


@Analista.route('/models/periods/<int:programa>')
@login_required
def get_periods_program(programa):
    status, body = get(f'desertion/students/periods/programa/{programa}')
    if status:
        return jsonify(body)
    return jsonify([])


def get_models(nombre=None, conjunto=None):
    user = session.get('user', {'correo': ''}).get('correo')
    endopoint = f'executions/ejecutor/{user}'
    if nombre:
        endopoint += f'?nombre={nombre}'
    elif conjunto:
        endopoint += f'?conjunto={conjunto}'
    return get(endopoint)


def formulario_entrenar():
    periods = DataIES.get_periods_origen()
    status_f, body_f = get('faculties')
    status_p, body_p = get('programs')

    if status_f and status_p and periods:
        return render_template(endopoint+'crear.html', faculties=body_f, programs=body_p)

    if not status_f and not status_p:
        error = {**body_f, **body_p}
    elif not status_f:
        error = body_f
    else:
        error = body_p
    return render_template(
        'utils/mensaje.html',
        mensaje='No se pudieron cargar las programs y las faculties',
        submensaje=error
    )

web/views/sets.py
import traceback
import pandas as pd
import os
import json
import logging
import utils.dashboards.data_ies as DataIES

from flask import request, session, Blueprint, render_template, redirect, send_file, url_for, jsonify, flash
from dotenv import load_dotenv
from ast import literal_eval
from googletrans import Translator

from utils.model import prepare_data, verify_data, execute_model
from views.auth import login_required
from services.API import get, post, put

from utils.mixins import actualizar_state, save_archivo, save_ejecucion, save_preparacion, get_now_date, obtener_archivo_excel, obtener_nombre_conjunto

model_logger = logging.getLogger('model_logger')
error_logger = logging.getLogger('error_logger')

load_dotenv()

Set = Blueprint('Set', __name__)

endopoint = 'sets/'

upload_folder = os.getcwd()+'/uploads'

translator = Translator()


@Set.route('')
@Set.route('/')
@Set.route('/crudos')
@Set.route('/crudos/')
@login_required
def crudos():
    return get_list('crudos')


@Set.route('/procesados')
@Set.route('/procesados/')
@Set.route('/procesados/<conjunto>')
@login_required
def procesados(conjunto=None):
    if conjunto:
        return get_list('procesados', str(conjunto))
    return get_list('procesados')


def get_list(estado, conjunto=None):
    user = session.get('user', {'correo': ''}).get('correo')
    status_p, body_p = get('programs')
    status_c, body_c = get(
        f'sets/encargado/{user}?estado={estado}'
    )

    if status_c and status_p:
        if conjunto:
            body_c = [d for d in body_c if conjunto in d['nombre']]
        return render_template(
            endopoint+estado.replace(' ', '_')+'.html',
            sets=body_c,
            programs=body_p
        )

    if not status_c and not status_p:
        error = {**body_c, **body_p}
    elif not status_c:
        error = body_c
    else:
        error = body_p
    return render_template(
        endopoint+estado.replace(' ', '_')+'.html',
        sets=[],
        error=error
    )


@Set.route('/descargar/<estado>/<nombre>')
def download(estado, nombre):

    status_c, body_c = get('sets/'+nombre)
    if not status_c:
        return render_template('utils/mensaje.html', mensaje='No existe ese conjunto')

    if estado.lower() == 'crudos':
        nombre = 'C '+nombre
    elif estado.lower() == 'procesados':
        nombre = 'P '+nombre
    else:
        return render_template('utils/mensaje.html', mensaje='Estado del conjunto incorrecto')

    ruta = upload_folder+'/'+estado.lower()+'/'+nombre

    if os.path.exists(ruta+'.xlsx'):
        return send_file(ruta+'.xlsx', as_attachment=True)
    elif os.path.exists(ruta+'.xls'):
        return send_file(ruta+'.xls', as_attachment=True)
    else:
        return render_template('utils/mensaje.html', mensaje='No se encontro el archivo a descargar')


@Set.route('/crear')
@Set.route('/crear/')
@login_required
def post_create():
    periods = DataIES.get_periods_origen()
    status_f, body_f = get('faculties')
    status_p, body_p = get('programs')

    if status_f and status_p and periods:
        return render_template(endopoint+'crear.html', faculties=body_f, programs=body_p)
    elif not status_f and not status_p:
        error = {**body_f, **body_p}
    elif not status_f:
        error = body_f
    else:
        error = body_p
    return render_template('utils/mensaje.html', mensaje='No se pudieron cargar las programs y las faculties', submensaje=error)


@Set.route('crear/periods/programa/<int:programa>')
@login_required
def get_periods_program(programa):
    status, body = get(
        'desertion/students/periods/programa/{}'.format(programa))
    if status:
        return jsonify(body)
    return jsonify([])


@Set.route('/detalle', methods=['POST'])
@login_required
def detalle():
    # Obtener Lo valores del formulario
    body = dict(request.values)
    conjunto = literal_eval(body['conjunto'])
    # Consultas para mostrar info
    status_f, body_f = get('faculties')
    status_p, body_p = get('programs')
    status_u, body_u = get('users')

    if status_p and status_f and status_u and conjunto:
        return render_template(endopoint+'detalle.html', faculties=body_f, programs=body_p, users=body_u, c=conjunto)
    elif not status_f and not status_p and not status_u:
        error = {**body_f, **body_p, **body_u}
    elif not status_f:
        error = body_f
    elif not status_p:
        error = body_p
    elif not conjunto:
        return render_template('utils/mensaje.html', mensaje='No se encontro un conjunto para detallar')
    else:
        error = body_u
    return render_template('utils/mensaje.html', mensaje='No se pudieron cargar los datos para detallar el conjunto', submensaje=error)


@Set.route('/crear', methods=['POST'])
@Set.route('/crear/', methods=['POST'])
@login_required
def post_save(conjunto=None):
    if not conjunto:
        # Obtener Lo valores del formulario
        conjunto = dict(request.values)
    # Preparar conjunto para la insercion
    del conjunto['faculty']

    # TODO NEW! version 2 v2.0.0
    session['period_closed'] = (conjunto.get('period_closed') == 'on')
    if session.get('period_closed'):
        del conjunto['period_closed']

    conjunto['estado'] = 'Crudos'
    conjunto['periodoInicial'] = int(conjunto['periodoInicial'])
    conjunto['periodoFinal'] = int(conjunto['periodoFinal'])
    conjunto['programa'] = int(conjunto['programa'])
    conjunto['encargado'] = session['user']['correo']

    tipo = conjunto.get('tipo', 'consulta')
    archivo = request.files.get('archivo')
    ruta = upload_folder+'/crudos'

    # Guardar archivo en Upload folder

    ############# ARCHIVO ##############
    if (archivo and archivo.filename and tipo == 'excel'):
        extension = '.'+archivo.filename.split('.')[1]
        # Guardar archivo de excel

        if extension not in ['.xls', '.xlsx']:
            return render_template('utils/mensaje.html', mensaje='Extension de archivo incorrecta: '+str(extension), submensaje='Solo se permiten archivos excel .xls & xlsx')

        # VERIFICACION de formato
        data = pd.read_excel(archivo)
        validacion, mensaje_error, data_verificada, periodoInicial = verify_data(
            data, conjunto.get('periodoInicial'), conjunto.get('periodoFinal'), conjunto.get('programa'))
        conjunto['periodoInicial'] = periodoInicial

        # Obtener nombre del conjunto desde el api
        nombre, numero = obtener_nombre_conjunto(conjunto)
        if not nombre:
            return numero
        archivo_save = 'C ' + nombre + '.xlsx'

        if validacion:
            try:
                data_verificada.to_excel(
                    ruta+'/'+archivo_save,
                    engine='openpyxl',
                    index=False
                )
            except Exception as e:
                error_logger.error(e)
                return render_template('utils/mensaje.html', mensaje='Ocurrió un error guardando el conjunto de datos')
        else:
            return render_template('utils/mensaje.html', mensaje='Incorrecto el formato de la fuente de datos', submensaje=mensaje_error)

    ############# CONSULTA ##############
    # elif tipo == 'consulta':
    else:
        # Obtener datos de los students en ese programs y periods
        endpoint_conjunto = 'desertion/students/set/{}/{}/{}'
        endpoint_conjunto_values = endpoint_conjunto.format(
            conjunto['programa'], conjunto['periodoInicial'], conjunto['periodoFinal'])
        status, body = get(endpoint_conjunto_values)
        if status:
            data = pd.DataFrame(body)
        else:
            return render_template('utils/mensaje.html', mensaje='Consulta fallida a la base de datos')

        # VERIFICACION de formato
        validacion, mensaje_error, data_verificada, periodoInicial = verify_data(
            data, conjunto.get('periodoInicial'), conjunto.get('periodoFinal'), conjunto.get('programa'))
        conjunto['periodoInicial'] = periodoInicial

        # Obtener nombre del conjunto desde el api
        nombre, numero = obtener_nombre_conjunto(conjunto)
        if not nombre:
            return numero
        archivo_save = 'C ' + nombre + '.xlsx'

        if validacion:
            # Guardar tabla sql como excel
            try:
                data_verificada.to_excel(
                    ruta+'/'+archivo_save,
                    engine='openpyxl',
                    index=False
                )
            except Exception as e:
                error_logger.error(e)
                return render_template('utils/mensaje.html', mensaje='Ocurrió un error guardando el conjunto de datos')
        else:
            return render_template('utils/mensaje.html', mensaje='Incorrecto el formato de la fuente de datos', submensaje=mensaje_error)
    # else:
    #     return render_template('utils/mensaje.html', mensaje='Formulario incorrecto', submensaje='Verifica el formulario de creacion o notifica al Administrador del sistema')

    # Guardar registro de conjunto en la BD
    conjunto['nombre'] = nombre
    conjunto['numero'] = numero
    status, body = post('sets', conjunto)

    # TODO DEPRECATED! version 1 v1.5.0
    # if status:
    #     return redirect(url_for('Set.crudos'))

    # TODO NEW! version 2 v2.0.0
    if status:
        # preparar() luego de post_save()
        return preparar(conjunto)

    return render_template('utils/mensaje.html', mensaje='No se pudo save el conjunto', submensaje=body)


@Set.route('/preparar', methods=['POST'])
@login_required
def preparar(conjunto=None):
    if not conjunto:
        # Obtener Lo valores del formulario
        body = dict(request.values)
        conjunto = literal_eval(body['conjunto'])

    nombre = conjunto['nombre']

    # Actualizar conjunto de datos de crudo a en proceso
    act_state = actualizar_state(nombre, 'En Proceso')
    if act_state:
        return act_state

    # Crear prepraracion
    preparacion = {}

web/templates/analist/models/list.html
{% include 'components/header.html' %} {% include 'components/sidebar.html' %}

<h4>
  Modelos de Deserción
  <i class="fas fa-robot fa-sm ml-1"></i>
</h4>
<br />

<!-- Input de filtrado -->
<div class="row ml-1 mt-2">
  &nbsp;<i class="fas fa-filter mr-2 mt-2"></i>&nbsp;
  <input
    type="text"
    class="form-control form-control-sm w-25"
    id="filtroTabla"
    placeholder="Filtrar tabla..."
  />
</div>
<br />

<!-- Tabla -->
<div class="table-responsive-sm">
  <table class="table table-hover table-sm" id="tabla">
    <thead>
      <tr class="border-top-0">
        <th scope="col" class="border-top-0">
        
        </th>
        <th scope="col" class="col-5 border-top-0 sortable" data-sort="programa"  class="" data-sort="name">
          <center><i>Program</i></center>
        </th>
        <th scope="col" class="col-1 border-top-0 sortable" data-sort="info">
          <center><i>Info</i></center>
        </th>
        <th scope="col" class="col-3 ml-5 border-top-0 sortable" data-sort="clasificador">
          <center><i>Clasificador</i></center>
        </th>
        <th scope="col" class="col-1 border-top-0 sortable" data-sort="precisión">
          <center><i>Precisión</i></center>
        </th>
        <th scope="col" class="col-1 border-top-0 sortable" data-sort="desertion">
          <center>
            <i>
                Deserción 
            </i>
          </center>
        </th>
        <th scope="col" class="col-1 border-top-0"></th>
      </tr>
    </thead>
    <tbody>
      {% for m in models %} {% if m.estado=='Exitosa' and m.results.tipo ==
      'Entrenamiento' %}
      {% set info_array = m.conjunto.split(' ')[1:] %}
      <tr>
        <td>
          <h6 >
            {{ info_array[2:3][0] }}
          </h6>
        </td>
        <td>
          <center>{{m.results.programa}}</center>
        </td>
        <td>
          
          <center>{{ info_array[:2]|join(' ') }} 
        </center>
        </td>

        <td>
          <center>{{ m.results.clasificador }}</center>
        </td>

        <td>
          <center>
            {{ '%0.0f' % m.results.precision|float }}% {% if
            (m.results.precision|float) < 85.00 %}

            <i
              class="fa fa-solid fa-exclamation-triangle fa-lg text-warning border-dark"
              data-toggle="tooltip"
              data-html="true"
              data-placement="bottom"
              style="cursor: pointer"
              title="La precisión del model no es muy alta, Ya que esta por debajo del 85%<br>Para estar mas seguro se recomienda crear otro con mas datos de entrenamiento."
            ></i>
            {% endif %}
          </center>
        </td>

        <td>
          {% set proc = m.results.desercion_prevista * 100 %}

          <center>
            ~ {{ '%0.0f' % proc|float }}% {% if m.results.desercion_prevista >
            0.15 %}
            <i
              class="fa fa-solid fa-exclamation-triangle fa-lg text-danger border-dark"
              data-toggle="tooltip"
              data-html="true"
              data-placement="bottom"
              title="Deserción estudiantil por encima del 15% <br>Pudo ocurrir un error de entrenamiento<br>Si es necesario, cree otro."
            ></i>
            {% endif %}
          </center>
        </td>

        <td>
          <!-- ACCCIONES -->
          <div class="row d-flex justify-content-center">
            

            <!-- Entrenamiento-->
            <div class="btn-group" role="group" aria-label="Basic example">
              <form
                action="{{url_for('Analista.entrenamientos')}}"
                method="GET"
              >
                <input type="hidden" name="model" value="{{m.conjunto}}" />
                <button
                  type="submit"
                  data-toggle="tooltip"
                  data-html="true"
                  data-placement="bottom"
                  title="Ver Entrenamientos"
                  class="btn btn-outline-dark btn-sm submit"
                  role="status"
                >
                  <i class="fa fa-sm fa-dumbbell"></i>
                </button>
              </form>
            </div>
            
            &nbsp;&nbsp;

            <!-- PREDECIR -->
            <form action="{{url_for('Analista.predecir')}}" method="POST">
              <input type="hidden" name="model" value="{{m}}" />
              <!-- Boton para predecir con un model -->
              <button
                type="submit"
                data-toggle="tooltip"
                data-html="true"
                data-placement="bottom"
                title="Predecir"
                class="btn my-primary text-white border border-white btn-sm submit"
                role="status"
              >
                <i class="fa fa-flask fa-lg" aria-hidden="true"></i>
              </button>

              <button
                class="btn btn-outline-dark btn-sm btn-loading"
                type="button"
                style="display: none"
              >
                <i class="fas fa-spinner fa-spin fa-lg" aria-hidden="true"></i>
              </button>
            </form>



            <!-- DESCARGAR-->
            <!-- <form action="{{url_for('Analista.download')}}" method="POST">
              <input type="hidden" name="model" value="{{m.conjunto}}" />
              <button
                type="submit"
                data-toggle="tooltip"
                data-html="true"
                data-placement="bottom"
                title="Descargar Archivo"
                class="btn btn-sm btn-link text-dark"
                role="status"
              >
                <i class="fa fa-dark fa-file-download"></i>
              </button>
            </form> -->
          </div>
        </td>
      </tr>
      {% endif %} {% endfor %}
    </tbody>
  </table>
</div>

{% if error %}
<br />
{% with titulo='No se pudieron cargar los models',error=error %} {% include
"components/alert.html" %} {% endwith %}
<br />
{% endif %}

<br />

<a
  href="{{url_for('Analista.entrenar') }}"
  type="button"
  class="btn btn-dark text-white my-primary mt-4"
>
  Nuevo
  <i class="fa fa-robot ml-1"></i>
</a>

<script>
  // Cargando si se esta validando y guardando la data del model
  $(".submit").click(function () {
    handleModal(
      "Su model aparecera cuando acabe el proceso (recuerde refrescar la página)",
      "{{url_for('Analista.predicciones')}}"
    );
  });
</script>

{% include 'components/footer.html' %}

web/templates/analist/models/predict.html
{% include 'components/header.html' %} {% with menu='models' %} {% include
'components/sidebar.html' %} {% endwith %}

<span>
  <h4 class="ml-1 d-inline-block">Predecir</h4>
  <i class="fa fa-flask fa-lg ml-1"></i>
</span>

<form
  id="conjuntoForm"
  action="{{url_for('Analista.predecir_model')}}"
  method="POST"
  enctype="multipart/form-data"
  data-toggle="validator"
  class="jumbotron py-4 pr-2 bg-light"
  style="width: 65%"
>
  <div class="container w-75 px-2">
    <div class="form-group row">
      <div class="col-12">
        <label id="faculty_label">
          <i class="fa fa-university"></i>
          Faculty
        </label>
        <input
          class="form-control"
          name="faculty"
          value="{{model.results.faculty}}"
          required
          readonly
        />
      </div>
    </div>
    <div class="form-group row">
      <div class="col-12">
        <label for="programa">
          <i class="fa fa-graduation-cap"></i>
          Program
        </label>

        <input id="programa" value="{{model.results.idprograma}}" hidden />
        <input name="ejecucion" value="{{model}}" hidden />

        <input
          class="form-control"
          name="programa"
          value="{{model.results.programa}}"
          required
          readonly
        />
      </div>
    </div>

    <div class="form-group row">
      <div class="col-12">
        <label for="programa">
          <i class="fa fa-calendar"></i>
          Periodos de Entrenamiento
        </label>

        {% set periods = model.conjunto.split(' ')[1:3] %}

        <div class="d-flex">
          <input
            class="form-control mr-4"
            name="periodoInicial"
            value="{{periods[0]}}"
            required
            readonly
          />
          <input
            class="form-control"
            name="periodoFinal"
            value="{{periods[1]}}"
            required
            readonly
          />
        </div>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-12">
        <label for="programa">
          <i class="fa fa-robot"></i>
          Clasificador/ Algoritmo
        </label>

        <input
          class="form-control"
          name="clasificador"
          value="{{model.results.clasificador}}"
          required
          readonly
        />
      </div>
    </div>

    <div class="form-group row justify-content-center">
      <div class="col-5">
        <label>
          <i class="fa fa-calendar-alt"></i>
          Periodo a Predecir
        </label>
        <div class="pr-3">
          <select
            name="periodo"
            id="periodoID"
            class="periods-controls form-control input-sm mr-5"
            required
          >
            <option disabled selected hidden></option>
          </select>
        </div>
      </div>
      <script>
        //LLenar con periodos del programa

        $.ajax({
          url: "periods/" + $("#programa").val(),
          type: "GET",
          contentType: "application/json;charset=UTF-8",
          data: {},
          dataType: "json",
          success: function (data) {
            var periodo = document.getElementById("periodoID");
            var i = 1;
            data.forEach((p) => {
              periodo.options[i] = new Option(p, p);
              i = i + 1;
            });
          },
        });
      </script>
    </div>

    <!--Boton para validar campos-->
    <br />
    <div class="text-center">
      <button
        id="btn-submit"
        type="submit"
        class="btn btn-dark text-white my-primary submit"
      >
        Predecir
        <i class="fas fa-flask fa-sm ml-1"></i>
      </button>
      <button
        class="btn btn-dark text-white my-primary btn-loading"
        type="button"
        style="display: none"
      >
        <i
          class="fas fa-spinner fa-spin fa-lg text-white"
          aria-hidden="true"
        ></i>
        Cargando...
      </button>
    </div>
  </div>
</form>

<script>
  // Boton cargando si se esta validando y guardando la data del conjunto
  $("#btn-submit").click(function () {
    var validacion = $("#conjuntoForm")[0].checkValidity();
    if (validacion == true) {
      handleModal(
        "Su conjunto aparecera cuando acabe el proceso (recuerde refrescar la página)",
        "{{url_for('Set.crudos')}}"
      );
    }
  });
</script>

{% include 'components/footer.html' %}